CC=g++
CFLAGS=-g -c -Wall -std=c++14
LDFLAGS=
CLIENT_SOURCES=start_client.cpp client.cpp
CLIENT_OBJECTS=$(CLIENT_SOURCES:.cpp=.o)
CLIENT_EXECUTABLE=start_client

SERVER_SOURCES=server.cpp
SERVER_OBJECTS=$(SERVER_SOURCES:.cpp=.o)
SERVER_EXECUTABLE=server

all: $(CLIENT_SOURCES) $(CLIENT_EXECUTABLE) $(SERVER_SOURCES) $(SERVER_EXECUTABLE)

$(CLIENT_EXECUTABLE): $(CLIENT_OBJECTS)
	$(CC) $(LDFLAGS) $(CLIENT_OBJECTS) -o $@

$(SERVER_EXECUTABLE): $(SERVER_OBJECTS)
	$(CC) $(LDFLAGS) $(SERVER_OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm *.o $(CLIENT_EXECUTABLE) $(SERVER_EXECUTABLE)
